wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 30
weight_decay:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689223299.731589
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.5
      8:
      - 5
